/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   piece.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mdebelle <mdebelle@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2015/12/03 11:11:21 by mdebelle          #+#    #+#             */
/*   Updated: 2015/12/03 11:11:23 by mdebelle         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

int 	find_piece_type(char *str)
{

if (ft_strcmp ("...#...#...#...#", str) == 0)

else if (ft_strcmp("..#...#...#...#.", str) == 0)
else if (ft_strcmp(".#...#...#...#..", str) == 0)
else if (ft_strcmp("#...#...#...#...", str) == 0)
else if (ft_strcmp("####............", str) == 0)
else if (ft_strcmp("....####........", str) == 0)
else if (ft_strcmp("........####....", str) == 0)
else if (ft_strcmp("............####", str) == 0)
else if (ft_strcmp("###.#...........", str) == 0)
else if (ft_strcmp("....###.#.......", str) == 0)
else if (ft_strcmp("........###.#...", str) == 0)
else if (ft_strcmp(".###.#..........", str) == 0)
else if (ft_strcmp(".....###.#......", str) == 0)
else if (ft_strcmp(".........###.#..", str) == 0)
else if (ft_strcmp("###...#.........", str) == 0)
else if (ft_strcmp("....###...#.....", str) == 0)
else if (ft_strcmp("........###...#.", str) == 0)
else if (ft_strcmp(".###...#........", str) == 0)
else if (ft_strcmp(".....###...#....", str) == 0)
else if (ft_strcmp(".........###...#", str) == 0)
else if (ft_strcmp("#...###.........", str) == 0)
else if (ft_strcmp("....#...###.....", str) == 0)
else if (ft_strcmp("........#...###.", str) == 0)
else if (ft_strcmp("...#.###........", str) == 0)
else if (ft_strcmp(".......#.###....", str) == 0)
else if (ft_strcmp("...........#.###", str) == 0)
else if (ft_strcmp("##..#...#.......", str) == 0)
else if (ft_strcmp(".##..#...#......", str) == 0)
else if (ft_strcmp("..##..#...#.....", str) == 0)
else if (ft_strcmp("....##..#...#...", str) == 0)
else if (ft_strcmp(".....##..#...#..", str) == 0)
else if (ft_strcmp("......##..#...#.", str) == 0)
else if (ft_strcmp("##...#...#......", str) == 0)
else if (ft_strcmp(".##...#...#.....", str) == 0)
else if (ft_strcmp("..##...#...#....", str) == 0)
else if (ft_strcmp("....##...#...#..", str) == 0)
else if (ft_strcmp(".....##...#...#.", str) == 0)
else if (ft_strcmp("......##...#...#", str) == 0)
else if (ft_strcmp("##...##.........", str) == 0)
else if (ft_strcmp(".##...##........", str) == 0)
else if (ft_strcmp("....##...##.....", str) == 0)
else if (ft_strcmp(".....##...##....", str) == 0)
else if (ft_strcmp("........##...##.", str) == 0)
else if (ft_strcmp(".........##...##", str) == 0)
else if (ft_strcmp(".##.##..........", str) == 0)
else if (ft_strcmp("..##.##.........", str) == 0)
else if (ft_strcmp(".....##.##......", str) == 0)
else if (ft_strcmp("......##.##.....", str) == 0)
else if (ft_strcmp(".........##.##..", str) == 0)
else if (ft_strcmp("..........##.##.", str) == 0)
else if (ft_strcmp("#...##...#......", str) == 0)
else if (ft_strcmp(".#...##...#.....", str) == 0)
else if (ft_strcmp("..#...##...#....", str) == 0)
else if (ft_strcmp("....#...##...#..", str) == 0)
else if (ft_strcmp(".....#...##...#.", str) == 0)
else if (ft_strcmp("......#...##...#", str) == 0)
else if (ft_strcmp(".#..##..#.......", str) == 0)
else if (ft_strcmp("..#..##..#......", str) == 0)
else if (ft_strcmp("...#..##..#.....", str) == 0)
else if (ft_strcmp(".....#..##..#...", str) == 0)
else if (ft_strcmp("......#..##..#..", str) == 0)
else if (ft_strcmp(".......#..##..#.", str) == 0)
else if (ft_strcmp("###..#..........", str) == 0)
else if (ft_strcmp("....###..#......", str) == 0)
else if (ft_strcmp("........###..#..", str) == 0)
else if (ft_strcmp(".###..#.........", str) == 0)
else if (ft_strcmp(".....###..#.....", str) == 0)
else if (ft_strcmp(".........###..#.", str) == 0)
else if (ft_strcmp(".#..###.........", str) == 0)
else if (ft_strcmp(".....#..###.....", str) == 0)
else if (ft_strcmp(".........#..###.", str) == 0)
else if (ft_strcmp("..#..###........", str) == 0)
else if (ft_strcmp("......#..###....", str) == 0)
else if (ft_strcmp("..........#..###", str) == 0)
else if (ft_strcmp("#...##..#.......", str) == 0)
else if (ft_strcmp("....#...##..#...", str) == 0)
else if (ft_strcmp(".#...##..#......", str) == 0)
else if (ft_strcmp(".....#...##..#..", str) == 0)
else if (ft_strcmp("..#...##..#.....", str) == 0)
else if (ft_strcmp("......#...##..#.", str) == 0)
else if (ft_strcmp(".#..##...#......", str) == 0)
else if (ft_strcmp(".....#..##...#..", str) == 0)
else if (ft_strcmp("..#..##...#.....", str) == 0)
else if (ft_strcmp("......#..##...#.", str) == 0)
else if (ft_strcmp("...#..##...#....", str) == 0)
else if (ft_strcmp(".......#..##...#", str) == 0)
	
else if (ft_strcmp("##..##..........", str) == 0)
else if (ft_strcmp("....##..##......", str) == 0)
else if (ft_strcmp("........##..##..", str) == 0)
else if (ft_strcmp(".##..##.........", str) == 0)
else if (ft_strcmp(".....##..##.....", str) == 0)
else if (ft_strcmp(".........##..##.", str) == 0)
else if (ft_strcmp("..##..##........", str) == 0)
else if (ft_strcmp("......##..##....", str) == 0)
else if (ft_strcmp("..........##..##", str) == 0)
}
